name: Build APK

on: [push, pull_request]  # 触发条件，可以是 push、pull_request 或者其他事件

jobs:
  build:
    runs-on: ubuntu-latest  # 运行作业的虚拟环境
    steps:
    - uses: actions/checkout@v2  # 检出代码
    - name: Set up JDK 1.8  # 设置 JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build APK  # 打包 APK
      run: |
        ./gradlew assembleRelease  # 使用 Gradle 打包 APK
    - name: Upload APK  # 上传 APK 到 artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
